language: python
python:
 - '3.8'

before_script:
 - apt-get install firefox-geckodriver
 - pipenv install

services:
 - postgresql

env: DJANGO_SETTINGS_MODULE=healthier.settings.travis

script: 
 - python manage.py test