# Generated by Django 3.0.6 on 2020-05-19 08:53

from django.db import migrations

def import_data_from_json():
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('healthier', '0002_auto_20200519_1042'),
    ]

    operations = [
        migrations.RunPython(import_data_from_json),
    ]
