# Generated by Django 3.0.6 on 2020-05-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthier", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food_item",
            name="nova_grade",
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
    ]
